// <auto-generated />
using System;
using AsistMedAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AsistMedAPI.Migrations
{
    [DbContext(typeof(AsistMedContext))]
    [Migration("20250720172705_PrimeraMigracionLimpia")]
    partial class PrimeraMigracionLimpia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AsistMedAPI.Models.EvaluacionClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Alergias")
                        .HasColumnType("boolean")
                        .HasColumnName("alergias");

                    b.Property<bool?>("AntecedentesPatologicos")
                        .HasColumnType("boolean")
                        .HasColumnName("antecedentes_patologicos");

                    b.Property<bool?>("DolorAbdominal")
                        .HasColumnType("boolean")
                        .HasColumnName("dolor_abdominal");

                    b.Property<bool?>("Fatiga")
                        .HasColumnType("boolean")
                        .HasColumnName("fatiga");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evaluacion");

                    b.Property<bool?>("MedicamentosActuales")
                        .HasColumnType("boolean")
                        .HasColumnName("medicamentos_actuales");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("evaluacion_clinica");
                });

            modelBuilder.Entity("AsistMedAPI.Models.EvaluacionNutricional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadAguaDia")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_agua_dia");

                    b.Property<int?>("ComidasAlDia")
                        .HasColumnType("integer")
                        .HasColumnName("comidas_al_dia");

                    b.Property<bool?>("ConsumoUltraprocesados")
                        .HasColumnType("boolean")
                        .HasColumnName("consumo_ultraprocesados");

                    b.Property<bool?>("DesayunoDiario")
                        .HasColumnType("boolean")
                        .HasColumnName("desayuno_diario");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evaluacion");

                    b.Property<int?>("FrutasPorSemana")
                        .HasColumnType("integer")
                        .HasColumnName("frutas_por_semana");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<bool?>("Refrigerio")
                        .HasColumnType("boolean")
                        .HasColumnName("refrigerio");

                    b.Property<int?>("VerdurasPorSemana")
                        .HasColumnType("integer")
                        .HasColumnName("verduras_por_semana");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("evaluacion_nutricional");
                });

            modelBuilder.Entity("AsistMedAPI.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("dni");

                    b.Property<int>("Edad")
                        .HasColumnType("integer")
                        .HasColumnName("edad");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombres");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sexo");

                    b.HasKey("Id");

                    b.ToTable("paciente");
                });

            modelBuilder.Entity("AsistMedAPI.Models.PrediccionDetallePdf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiagnosticoFinal")
                        .HasColumnType("text")
                        .HasColumnName("diagnostico_final");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<string>("RecomendacionesClinicas")
                        .HasColumnType("text")
                        .HasColumnName("recomendaciones_clinicas");

                    b.Property<string>("RiesgosDetectados")
                        .HasColumnType("text")
                        .HasColumnName("riesgos_detectados");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("prediccion_detalle_pdf");
                });

            modelBuilder.Entity("AsistMedAPI.Models.PrediccionIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnfermedadPredicha")
                        .HasColumnType("text")
                        .HasColumnName("enfermedad_predicha");

                    b.Property<DateTime>("FechaPrediccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_prediccion");

                    b.Property<string>("HistorialDescriptivo")
                        .HasColumnType("text")
                        .HasColumnName("historial_descriptivo");

                    b.Property<string>("InformePdf")
                        .HasColumnType("text")
                        .HasColumnName("informe_pdf");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<double?>("PorcentajeConfianza")
                        .HasColumnType("double precision")
                        .HasColumnName("porcentaje_confianza");

                    b.Property<string>("RiesgoClinico")
                        .HasColumnType("text")
                        .HasColumnName("riesgo_clinico");

                    b.Property<string>("RiesgoDigestivo")
                        .HasColumnType("text")
                        .HasColumnName("riesgo_digestivo");

                    b.Property<string>("RiesgoNutricional")
                        .HasColumnType("text")
                        .HasColumnName("riesgo_nutricional");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("prediccion_ia");
                });

            modelBuilder.Entity("AsistMedAPI.Models.SignosVitales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int?>("FrecuenciaCardiaca")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia_cardiaca");

                    b.Property<int?>("FrecuenciaRespiratoria")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia_respiratoria");

                    b.Property<double?>("Glucosa")
                        .HasColumnType("double precision")
                        .HasColumnName("glucosa_mg_dl");

                    b.Property<double?>("IMC")
                        .HasColumnType("double precision")
                        .HasColumnName("imc");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<double?>("Peso")
                        .HasColumnType("double precision")
                        .HasColumnName("peso_kg");

                    b.Property<int?>("SaturacionOxigeno")
                        .HasColumnType("integer")
                        .HasColumnName("saturacion_oxigeno");

                    b.Property<double?>("Talla")
                        .HasColumnType("double precision")
                        .HasColumnName("talla_cm");

                    b.Property<double?>("Temperatura")
                        .HasColumnType("double precision")
                        .HasColumnName("temperatura");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("signos_vitales");
                });

            modelBuilder.Entity("AsistMedAPI.Models.SintomasDigestivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("ArdorEstomacal")
                        .HasColumnType("boolean")
                        .HasColumnName("ardor_estomacal");

                    b.Property<bool?>("DolorEstomacal")
                        .HasColumnType("boolean")
                        .HasColumnName("dolor_estomacal");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evaluacion");

                    b.Property<string>("FrecuenciaDolor")
                        .HasColumnType("text")
                        .HasColumnName("frecuencia_dolor");

                    b.Property<bool?>("Nausea")
                        .HasColumnType("boolean")
                        .HasColumnName("nausea");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<bool?>("SangradoDigestivo")
                        .HasColumnType("boolean")
                        .HasColumnName("sangrado_digestivo");

                    b.Property<bool?>("Vomito")
                        .HasColumnType("boolean")
                        .HasColumnName("vomito");

                    b.Property<string>("ZonaDolor")
                        .HasColumnType("text")
                        .HasColumnName("zona_dolor");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("sintomas_digestivos");
                });

            modelBuilder.Entity("AsistMedAPI.Models.EvaluacionClinica", b =>
                {
                    b.HasOne("AsistMedAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AsistMedAPI.Models.EvaluacionNutricional", b =>
                {
                    b.HasOne("AsistMedAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AsistMedAPI.Models.PrediccionDetallePdf", b =>
                {
                    b.HasOne("AsistMedAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AsistMedAPI.Models.PrediccionIA", b =>
                {
                    b.HasOne("AsistMedAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AsistMedAPI.Models.SignosVitales", b =>
                {
                    b.HasOne("AsistMedAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AsistMedAPI.Models.SintomasDigestivos", b =>
                {
                    b.HasOne("AsistMedAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
