// <auto-generated />
using System;
using AsistMedAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AsistMedAPI.Migrations
{
    [DbContext(typeof(AsistMedContext))]
    [Migration("20250801201008_AddObservacionesToEvaluacionNutricional")]
    partial class AddObservacionesToEvaluacionNutricional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AsistMedAPI.Models.EvaluacionClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Alergias")
                        .HasColumnType("boolean")
                        .HasColumnName("alergias");

                    b.Property<bool?>("AntecedenteDiabetesFamiliar")
                        .HasColumnType("boolean")
                        .HasColumnName("antecedente_diabetes_familiar");

                    b.Property<bool?>("AntecedenteEDA")
                        .HasColumnType("boolean")
                        .HasColumnName("antecedente_eda");

                    b.Property<bool?>("AntecedenteTabaquismo")
                        .HasColumnType("boolean")
                        .HasColumnName("antecedente_tabaquismo");

                    b.Property<bool?>("AntecedenteUsoAINS")
                        .HasColumnType("boolean")
                        .HasColumnName("antecedente_uso_ains");

                    b.Property<bool?>("Fatiga")
                        .HasColumnType("boolean")
                        .HasColumnName("fatiga");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evaluacion");

                    b.Property<bool?>("MedicamentosActuales")
                        .HasColumnType("boolean")
                        .HasColumnName("medicamentos_actuales");

                    b.Property<bool?>("Nauseas")
                        .HasColumnType("boolean")
                        .HasColumnName("nauseas");

                    b.Property<string>("ObservacionesGenerales")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_generales");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<bool?>("PerdidaPesoNoIntencional")
                        .HasColumnType("boolean")
                        .HasColumnName("perdida_peso_no_intencional");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("evaluacion_clinica");
                });

            modelBuilder.Entity("AsistMedAPI.Models.EvaluacionNutricional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadAguaDia")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_agua_dia");

                    b.Property<int?>("ComidasAlDia")
                        .HasColumnType("integer")
                        .HasColumnName("comidas_al_dia");

                    b.Property<bool?>("ConsumoUltraprocesados")
                        .HasColumnType("boolean")
                        .HasColumnName("consumo_ultraprocesados");

                    b.Property<bool?>("DesayunoDiario")
                        .HasColumnType("boolean")
                        .HasColumnName("desayuno_diario");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evaluacion");

                    b.Property<int?>("FrutasPorSemana")
                        .HasColumnType("integer")
                        .HasColumnName("frutas_por_semana");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<bool?>("Refrigerio")
                        .HasColumnType("boolean")
                        .HasColumnName("refrigerio");

                    b.Property<int?>("VerdurasPorSemana")
                        .HasColumnType("integer")
                        .HasColumnName("verduras_por_semana");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("evaluacion_nutricional");
                });

            modelBuilder.Entity("AsistMedAPI.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("dni");

                    b.Property<int>("Edad")
                        .HasColumnType("integer")
                        .HasColumnName("edad");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombres");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sexo");

                    b.HasKey("Id");

                    b.ToTable("paciente");
                });

            modelBuilder.Entity("AsistMedAPI.Models.PrediccionDetallePdf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiagnosticoFinal")
                        .HasColumnType("text")
                        .HasColumnName("diagnostico_final");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<string>("RecomendacionesClinicas")
                        .HasColumnType("text")
                        .HasColumnName("recomendaciones_clinicas");

                    b.Property<string>("RiesgosDetectados")
                        .HasColumnType("text")
                        .HasColumnName("riesgos_detectados");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("prediccion_detalle_pdf");
                });

            modelBuilder.Entity("AsistMedAPI.Models.PrediccionIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnfermedadPredicha")
                        .HasColumnType("text")
                        .HasColumnName("enfermedad_predicha");

                    b.Property<DateTime>("FechaPrediccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_prediccion");

                    b.Property<string>("HistorialDescriptivo")
                        .HasColumnType("text")
                        .HasColumnName("historial_descriptivo");

                    b.Property<string>("InformePdf")
                        .HasColumnType("text")
                        .HasColumnName("informe_pdf");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<double?>("PorcentajeConfianza")
                        .HasColumnType("double precision")
                        .HasColumnName("porcentaje_confianza");

                    b.Property<string>("RiesgoClinico")
                        .HasColumnType("text")
                        .HasColumnName("riesgo_clinico");

                    b.Property<string>("RiesgoDigestivo")
                        .HasColumnType("text")
                        .HasColumnName("riesgo_digestivo");

                    b.Property<string>("RiesgoNutricional")
                        .HasColumnType("text")
                        .HasColumnName("riesgo_nutricional");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("prediccion_ia");
                });

            modelBuilder.Entity("AsistMedAPI.Models.SignosVitales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasAnnotation("Relational:JsonPropertyName", "fechaRegistro");

                    b.Property<int?>("FrecuenciaCardiaca")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia_cardiaca")
                        .HasAnnotation("Relational:JsonPropertyName", "frecuenciaCardiaca");

                    b.Property<int?>("FrecuenciaRespiratoria")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia_respiratoria")
                        .HasAnnotation("Relational:JsonPropertyName", "frecuenciaRespiratoria");

                    b.Property<double?>("Glucosa")
                        .HasColumnType("double precision")
                        .HasColumnName("glucosa_mg_dl")
                        .HasAnnotation("Relational:JsonPropertyName", "glucosa");

                    b.Property<double?>("IMC")
                        .HasColumnType("double precision")
                        .HasColumnName("imc")
                        .HasAnnotation("Relational:JsonPropertyName", "imc");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<double?>("Peso")
                        .HasColumnType("double precision")
                        .HasColumnName("peso_kg")
                        .HasAnnotation("Relational:JsonPropertyName", "peso");

                    b.Property<int?>("PresionDiastolica")
                        .HasColumnType("integer")
                        .HasColumnName("presion_diastolica")
                        .HasAnnotation("Relational:JsonPropertyName", "presionDiastolica");

                    b.Property<int?>("PresionSistolica")
                        .HasColumnType("integer")
                        .HasColumnName("presion_sistolica")
                        .HasAnnotation("Relational:JsonPropertyName", "presionSistolica");

                    b.Property<int?>("SaturacionOxigeno")
                        .HasColumnType("integer")
                        .HasColumnName("saturacion_oxigeno")
                        .HasAnnotation("Relational:JsonPropertyName", "saturacionOxigeno");

                    b.Property<double?>("Talla")
                        .HasColumnType("double precision")
                        .HasColumnName("talla_cm")
                        .HasAnnotation("Relational:JsonPropertyName", "talla");

                    b.Property<double?>("Temperatura")
                        .HasColumnType("double precision")
                        .HasColumnName("temperatura")
                        .HasAnnotation("Relational:JsonPropertyName", "temperatura");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("signos_vitales");
                });

            modelBuilder.Entity("AsistMedAPI.Models.SintomasDigestivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AntecedenteColitis")
                        .HasColumnType("boolean")
                        .HasColumnName("antecedente_colitis");

                    b.Property<bool?>("AntecedenteGastritis")
                        .HasColumnType("boolean")
                        .HasColumnName("antecedente_gastritis");

                    b.Property<bool?>("AntecedenteUlcera")
                        .HasColumnType("boolean")
                        .HasColumnName("antecedente_ulcera");

                    b.Property<bool?>("ArdorEstomacal")
                        .HasColumnType("boolean")
                        .HasColumnName("ardor_estomacal");

                    b.Property<bool?>("CambiosDeposiciones")
                        .HasColumnType("boolean")
                        .HasColumnName("cambios_deposiciones");

                    b.Property<bool?>("Diarrea")
                        .HasColumnType("boolean")
                        .HasColumnName("diarrea");

                    b.Property<bool?>("DistensionAbdominal")
                        .HasColumnType("boolean")
                        .HasColumnName("distension_abdominal");

                    b.Property<bool?>("DolorAbdominal")
                        .HasColumnType("boolean")
                        .HasColumnName("dolor_abdominal");

                    b.Property<int?>("DuracionSintomasDias")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_sintomas_dias");

                    b.Property<bool?>("Estreñimiento")
                        .HasColumnType("boolean")
                        .HasColumnName("estrenimiento");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evaluacion");

                    b.Property<bool?>("InfeccionesRecientes")
                        .HasColumnType("boolean")
                        .HasColumnName("infecciones_recientes");

                    b.Property<bool?>("Nausea")
                        .HasColumnType("boolean")
                        .HasColumnName("nausea");

                    b.Property<string>("NotasEspecialista")
                        .HasColumnType("text")
                        .HasColumnName("notas_especialista");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<bool?>("PerdidaApetito")
                        .HasColumnType("boolean")
                        .HasColumnName("perdida_apetito");

                    b.Property<bool?>("ReflujoGastroesofagico")
                        .HasColumnType("boolean")
                        .HasColumnName("reflujo_gastroesofagico");

                    b.Property<bool?>("SangradoDigestivo")
                        .HasColumnType("boolean")
                        .HasColumnName("sangrado_digestivo");

                    b.Property<bool?>("Vomito")
                        .HasColumnType("boolean")
                        .HasColumnName("vomito");

                    b.Property<string>("ZonaDolorAbdominal")
                        .HasColumnType("text")
                        .HasColumnName("zona_dolor_abdominal");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("sintomas_digestivos");
                });

            modelBuilder.Entity("AsistMedAPI.Models.EvaluacionClinica", b =>
                {
                    b.HasOne("AsistMedAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AsistMedAPI.Models.EvaluacionNutricional", b =>
                {
                    b.HasOne("AsistMedAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AsistMedAPI.Models.PrediccionDetallePdf", b =>
                {
                    b.HasOne("AsistMedAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AsistMedAPI.Models.PrediccionIA", b =>
                {
                    b.HasOne("AsistMedAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AsistMedAPI.Models.SignosVitales", b =>
                {
                    b.HasOne("AsistMedAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AsistMedAPI.Models.SintomasDigestivos", b =>
                {
                    b.HasOne("AsistMedAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
