// <auto-generated />
using AsistMedAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AsistMedAPI.Migrations
{
    [DbContext(typeof(AsistMedContext))]
    [Migration("20250805152625_InicialPrediccionIA")]
    partial class InicialPrediccionIA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AsistMedAPI.Models.PrediccionIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AntecedenteEDA")
                        .HasColumnType("boolean");

                    b.Property<bool>("AntecedenteTabaquismo")
                        .HasColumnType("boolean");

                    b.Property<bool>("AntecedenteUsoAines")
                        .HasColumnType("boolean");

                    b.Property<bool>("AntecedentesDiabetesFamiliar")
                        .HasColumnType("boolean");

                    b.Property<bool>("CambiosDeposiciones")
                        .HasColumnType("boolean");

                    b.Property<string>("DiagnosticoFinal")
                        .HasColumnType("text");

                    b.Property<string>("DiagnosticoGastro")
                        .HasColumnType("text");

                    b.Property<string>("DiagnosticoMedico")
                        .HasColumnType("text");

                    b.Property<string>("DiagnosticoNutri")
                        .HasColumnType("text");

                    b.Property<bool>("Diarrea")
                        .HasColumnType("boolean");

                    b.Property<bool>("DistensionAbdominal")
                        .HasColumnType("boolean");

                    b.Property<bool>("DolorAbdominal")
                        .HasColumnType("boolean");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<bool>("Fatiga")
                        .HasColumnType("boolean");

                    b.Property<int>("FrecuenciaCardiaca")
                        .HasColumnType("integer");

                    b.Property<int>("FrecuenciaRespiratoria")
                        .HasColumnType("integer");

                    b.Property<double>("GlucosaCapilar")
                        .HasColumnType("double precision");

                    b.Property<bool>("InfeccionesRecientes")
                        .HasColumnType("boolean");

                    b.Property<bool>("Nauseas")
                        .HasColumnType("boolean");

                    b.Property<bool>("PerdidaPeso")
                        .HasColumnType("boolean");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.Property<string>("Porcentaje")
                        .HasColumnType("text");

                    b.Property<double>("PresionDiastolica")
                        .HasColumnType("double precision");

                    b.Property<double>("PresionSistolica")
                        .HasColumnType("double precision");

                    b.Property<bool>("ReflujoGastroesofagico")
                        .HasColumnType("boolean");

                    b.Property<bool>("SangradoDigestivo")
                        .HasColumnType("boolean");

                    b.Property<double>("SaturacionOxigeno")
                        .HasColumnType("double precision");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<double>("Talla")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperatura")
                        .HasColumnType("double precision");

                    b.Property<bool>("TieneAlergias")
                        .HasColumnType("boolean");

                    b.Property<string>("VariableAuxiliar")
                        .HasColumnType("text");

                    b.Property<bool>("Vomitos")
                        .HasColumnType("boolean");

                    b.Property<string>("ZonaDolorAbdominal")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PrediccionesIA");
                });
#pragma warning restore 612, 618
        }
    }
}
